### ISSUE TITLE
Wrong using step 3 in README (fetch.sh ... txt file)

### ISSUE THREAD

**Issue by karekaa** [lentinj/ie-vm#12]
In the README.rst there are specified as point 3. to:
"Run fetch.sh http://../IE11.Win8.1.For.LinuxVirtualBox.txt and wait. The multiple wgets will fight for the screen somewhat."
This does not play, while doing the same for a according .zip file, will download the VM-container

**Comment by lentinj** [comment]
Thanks, seems the old ``.txt`` files have now gone completely, although they are still in Microsoft's VM selection code.

The above modifies ie-urls.sh to not display them, and modifies the README to avoid confusion.

**Comment by karekaa** [comment]
Wow!
I'm impressed - fixed in just minutes after reporting ...
:-D

Sincerely / Med vennlig hilsen,

Kjell Arne Rekaa
Jacob Aalls gt 31 A, N-0364 Oslo
Mobile: +47-90 88 99 06
Blogs: http://les-kar.blogspot.com/, https://mobilkar.wordpress.com/
Twitter: kjell_arne <http://twitter.com/kjell_arne>


Den fre. 9. nov. 2018 kl. 12:21 skrev Jamie Lentin <notifications@github.com

**Comment by lentinj** [comment]
*bows*
